### ISSUE TITLE
Arilux LC06 set up in CW/WW mode

### ISSUE THREAD

**Issue by saabirsa** [NorthernMan54/homebridge-tasmota#3]
I have a Arilux LC06 set up in CW/WW mode and it would be great if the plugin could be updated so that this can be detected as part of this plugin.
`setoption19` is set to `1`, and the module can be used within HA at the moment. The module config on Tasmota is as follows;
```
GPIO0: Button 1 (17)
GPIO5: PWM1 (37)
GPIO15: PWM2 (38)
```
All other GPIO's are set as `None (0)`

Probably an overload of information (but within it, hopefully something useful!) - here are the entities and triggers data on HA.

'Upstairs Hallway Light' (light.tasmota)
MQTT discovery data:
Topic: `homeassistant/light/DC07A6_LI_1/config`
Payload
```
name: Upstairs Hallway Light
state_topic: tele/upstairs_hallway_light/STATE
availability_topic: tele/upstairs_hallway_light/LWT
payload_available: Online
payload_not_available: Offline
command_topic: cmnd/upstairs_hallway_light/POWER
value_template: '{{value_json.POWER}}'
payload_off: 'OFF'
payload_on: 'ON'
unique_id: DC07A6_LI_1
device:
  identifiers:
    - DC07A6
brightness_command_topic: cmnd/upstairs_hallway_light/Dimmer
brightness_state_topic: tele/upstairs_hallway_light/STATE
brightness_scale: 100
on_command_type: brightness
brightness_value_template: '{{value_json.Dimmer}}'
color_temp_command_topic: cmnd/upstairs_hallway_light/CT
color_temp_state_topic: tele/upstairs_hallway_light/STATE
color_temp_value_template: '{{value_json.CT}}'
platform: mqtt
```
Subscribed topics:
`tele/upstairs_hallway_light/LWT`
2 most recently received message(s)
```
Received 14:55:26
QoS: 0, Retained
Payload: Online
Received 14:55:26
QoS: 0, Retained
Payload: Online
```
`tele/upstairs_hallway_light/STATE`
4 most recently received message(s)
```
Received 14:56:29
QoS: 0
Payload: Time: '2020-09-03T14:56:30'
Uptime: '0T19:27:42'
UptimeSec: 70062
Heap: 26
SleepMode: Dynamic
Sleep: 50
LoadAvg: 19
MqttCount: 1
POWER: 'OFF'
Dimmer: 0
Color: '0,0'
White: 0
CT: 222
Channel:
  - 0
  - 0
Fade: 'OFF'
Speed: 1
LedTable: 'ON'
Wifi:
  AP: 1
  SSId: XXXXX
  BSSId: 'XXXXX'
  Channel: 1
  RSSI: 84
  Signal: -58
  LinkCount: 1
  Downtime: '0T00:00:03'
```
SNIP

'Upstairs Hallway Light status' (sensor.tasmota_status)
MQTT discovery data:
Topic: `homeassistant/sensor/DC07A6_status/config`
Payload
```
name: Upstairs Hallway Light status
state_topic: tele/upstairs_hallway_light/HASS_STATE
availability_topic: tele/upstairs_hallway_light/LWT
payload_available: Online
payload_not_available: Offline
json_attributes_topic: tele/upstairs_hallway_light/HASS_STATE
unit_of_measurement: '%'
value_template: '{{value_json[''RSSI'']}}'
icon: 'mdi:information-outline'
unique_id: DC07A6_status
device:
  identifiers:
    - DC07A6
  name: Upstairs Hallway Light
  model: Arilux LC06 in CW/WW mode
  sw_version: 8.4.0.3(tasmota)
  manufacturer: Tasmota
platform: mqtt
```
Subscribed topics:
`tele/upstairs_hallway_light/LWT`
1 most recently received message(s)
```
Received 14:55:26
QoS: 0, Retained
Payload: Online
```
`tele/upstairs_hallway_light/HASS_STATE`
3 most recently received message(s)
```
Received 14:58:50
QoS: 0
Payload: Version: 8.4.0.3(tasmota)
BuildDateTime: '2020-08-30T13:53:50'
Module or Template: Arilux LC06 in CW/WW mode
RestartReason: Software/System restart
Uptime: '0T19:30:03'
Hostname: Upstairs Hallway Light
IPAddress: XXXXX
RSSI: '86'
Signal (dBm): '-57'
WiFi LinkCount: 1
WiFi Downtime: '0T00:00:03'
MqttCount: 1
LoadAvg: 19
Received 15:03:50
```
SNIP

Triggers
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_SINGLE/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"SINGLE"}'
type: button_short_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_DOUBLE/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"DOUBLE"}'
type: button_double_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_TRIPLE/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"TRIPLE"}'
type: button_triple_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_QUAD/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"QUAD"}'
type: button_quadruple_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_PENTA/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"PENTA"}'
type: button_quintuple_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```
MQTT discovery data:
Topic: `homeassistant/device_automation/DC07A6_BTN_1_HOLD/config`
Payload
```
automation_type: trigger
topic: stat/upstairs_hallway_light/BUTTON1T
payload: '{"TRIG":"HOLD"}'
type: button_long_press
subtype: button_1
device:
  identifiers:
    - DC07A6
platform: mqtt
```

If there's any further information that could help, let me know.

Cheers.
